### ISSUE TITLE
Remove erroneous JAR files causing command-line failure in build 1.10.0

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS-Incubator/transform#16]
**Describe the bug**
I have just upgraded to transform 1.10 and on running I get:

```
$ transform
/home/mbentley/Dropbox/software/pds/transform-1.10.0/bin/transform: 55: [: /home/mbentley/Dropbox/software/pds/transform-1.10.0/lib/transform-1.10.0-sources.jar: unexpected operator
-f flag option is required.
```

If I try to list objects in a file:
```
$ transform -O fits_test_j_scale.xml 
/home/mbentley/Dropbox/software/pds/transform-1.10.0/bin/transform: 55: [: /home/mbentley/Dropbox/software/pds/transform-1.10.0/lib/transform-1.10.0-sources.jar: unexpected operator
Exception occurred while parsing label: Problem while parsing input label: "transform-1.10.0-sources.jar" is not a label. Could not find the PDS_VERSION_ID in the first line.
```
and even more weird behaviour if I try to actually convert something.

**Desktop (please complete the following information):**
 - OS: linux
 - Version: ubuntu 18.04

**Additional context**
- Java: Oracle Java 8

**Comment by jordanpadams** [comment]
@msbentley sorry for the bug. new release in process if you are interested in testing out. albeit, there really aren't any new features or fixes since the build previous to 1.10.0

**Comment by msbentley** [comment]
Thanks @jordanpadams this may be user error, but I'm not seeing any change in the behaviour wrt the above:

```
$ ./transform
./transform: 55: [: /home/mbentley/Dropbox/software/pds/transform-1.11.0/lib/transform-1.11.0-javadoc.jar: unexpected operator
-f flag option is required.
```
Any clues?

**Comment by jordanpadams** [comment]
@msbentley nope. you are right. i actually have no idea how validate and our other tools are working but releasing a new version now
